core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_personne:
    resource: "@CoreBundle/Resources/config/routing/personne.yml"
    prefix: /personne
    
core_entreprise:
    resource: "@CoreBundle/Resources/config/routing/entreprise.yml"
    prefix: /entreprise
    
core_rdv:
    resource: "@CoreBundle/Resources/config/routing/rdv.yml"
    prefix: /rdv
    
core_rendezvous:
    resource: "@CoreBundle/Resources/config/routing/rendezvous.yml"
    prefix: /rendezvous
    
core_contrat:
    resource: "@CoreBundle/Resources/config/routing/contrat.yml"
    prefix: /contrat