promo_index:
    path:     /
    defaults: { _controller: "CoreBundle:Promo:index" }
    methods:  GET

promo_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:Promo:show" }
    methods:  GET

promo_new:
    path:     /new
    defaults: { _controller: "CoreBundle:Promo:new" }
    methods:  [GET, POST]

promo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreBundle:Promo:edit" }
    methods:  [GET, POST]

promo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreBundle:Promo:delete" }
    methods:  DELETE

promo_conseil:
    path:     /{id}/conseil
    defaults: { _controller: "CoreBundle:Promo:conseil" }
    methods:  GET
