rendezvous_index:
    path:     /
    defaults: { _controller: "CoreBundle:Rendezvous:index" }
    methods:  GET

rendezvous_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:Rendezvous:show" }
    methods:  GET

rendezvous_new:
    path:     /new
    defaults: { _controller: "CoreBundle:Rendezvous:new" }
    methods:  [GET, POST]

rendezvous_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreBundle:Rendezvous:edit" }
    methods:  [GET, POST]

rendezvous_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreBundle:Rendezvous:delete" }
    methods:  DELETE
