<?php

namespace CoreBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllByPromo($idpromo) {
        $query = $this->_em->createQuery('SELECT p FROM CoreBundle:Personne p WHERE p.id = :id');
        $query->setParameter('id', $idpromo);

        return $query->getResult();
    }

}
